### ISSUE TITLE
[BugFix] Dashboard Calender Event - Homework not showing

### ISSUE THREAD

**Issue by CowsenF** [AAU-P5-Moodle/moodle-2#78]
What: The homeworks inside a homework instance are not shown on in calender event. If location is added the homework instance does not show at all
Where: Dashboard Calender - Block Homework 
Who: Students

![Image](https://github.com/user-attachments/assets/5c6bfb27-5323-4fbf-bf81-07be0f802780)

![Image](https://github.com/user-attachments/assets/9d5d0ce6-8c85-4610-bcb7-11c902c47a73)

**Comment by Dk1080** [comment]
Issue has been fixed with the new event linker implementation from #52
